spring.config.import=optional:file:.env[.properties]

spring.application.name=finnew-discovery-service
server.port=8761

#EUREKA
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

#HEALTH MONITORING - ACTUATOR
management.endpoints.web.exposure.include=health, metric, info

